<?php

return [
    'name' => 'SARVIX Technologies',
    'short_name' => 'SARVIX',
    'tagline' => 'Technology for Every Business.',
    'positioning' => 'One Technology Partner for Your Complete Business Journey.',
    'story' => 'Small Business → Digital Business → Growing Business',

    'contact' => [
        'phone' => env('SARVIX_PHONE', '+91 96246 8831'),
        'email' => env('SARVIX_EMAIL', 'hello@sarvixtechnologies.com'),
        'whatsapp' => env('SARVIX_WHATSAPP', '91962468831'),
        'whatsapp_message' => "Hi SARVIX,\nI'd like to know more about your technology solutions.",
        'whatsapp_package_message' => "Hi SARVIX,\nI'm interested in the {package} – {duration} Plan.\nPlease share more details.",
        'address' => env('SARVIX_ADDRESS', 'Ahmedabad, Gujarat, India'),
        'social' => [
            'linkedin' => env('SARVIX_LINKEDIN', '#'),
            'instagram' => env('SARVIX_INSTAGRAM', '#'),
            'facebook' => env('SARVIX_FACEBOOK', '#'),
        ],
    ],

    'seo' => [
        'default_title' => 'SARVIX Technologies | Technology for Every Business',
        'default_description' => 'SARVIX Technologies provides websites, eCommerce, custom software, AI automation and complete digital solutions for businesses.',
    ],

    'nav' => [
        ['label' => 'Home', 'route' => 'home'],
        ['label' => 'About', 'route' => 'about'],
        ['label' => 'Services', 'route' => 'services.index'],
        ['label' => 'Solutions', 'route' => 'solutions', 'type' => 'mega'],
        ['label' => 'Marketing Packages', 'route' => 'marketing-packages'],
        ['label' => 'Pricing', 'route' => 'pricing'],
        ['label' => 'Demos', 'route' => 'demos'],
        ['label' => 'Contact', 'route' => 'contact'],
    ],

    'nav_solutions' => [
        'business' => [
            ['label' => 'Kirana & Grocery', 'type' => 'anchor', 'slug' => 'kirana'],
            ['label' => 'Retail & Jewellery', 'type' => 'solution', 'slug' => 'retail'],
            ['label' => 'Professional Services', 'type' => 'solution', 'slug' => 'professional-services'],
            ['label' => 'eCommerce', 'type' => 'solution', 'slug' => 'ecommerce'],
            ['label' => 'Business Management', 'type' => 'solution', 'slug' => 'business-management'],
            ['label' => 'AI & Automation', 'type' => 'solution', 'slug' => 'ai-automation'],
        ],
        'industries' => [
            ['label' => 'Retail', 'slug' => 'retail'],
            ['label' => 'Restaurants & Food', 'slug' => 'food'],
            ['label' => 'Manufacturers', 'slug' => 'manufacturing'],
            ['label' => 'Wholesalers', 'slug' => 'wholesale'],
            ['label' => 'Professional Services', 'slug' => 'professional'],
            ['label' => 'Healthcare', 'slug' => 'healthcare'],
            ['label' => 'Education / Coaching', 'slug' => 'education'],
            ['label' => 'Real Estate', 'slug' => 'real-estate'],
            ['label' => 'Startups', 'slug' => 'startups'],
        ],
    ],

    'highlights' => [
        ['icon' => 'globe', 'title' => 'Web Solutions', 'text' => 'Business and corporate websites built to convert.'],
        ['icon' => 'layers', 'title' => 'Business Software', 'text' => 'CRM, ERP, inventory, billing and custom systems.'],
        ['icon' => 'spark', 'title' => 'AI & Automation', 'text' => 'Intelligent workflows that reduce repetitive work.'],
        ['icon' => 'trend', 'title' => 'Digital Growth', 'text' => 'Marketing, SEO and campaigns that support sales.'],
    ],

    'capabilities' => [
        ['value' => '6+', 'label' => 'Solution Areas'],
        ['value' => 'ONE', 'label' => 'Technology Partner'],
        ['value' => '5', 'label' => 'Growth Stages'],
        ['value' => 'E2E', 'label' => 'Digital Journey'],
    ],

    'services' => [
        [
            'slug' => 'web-development',
            'icon' => 'globe',
            'category' => 'Web Solutions',
            'title' => 'Website Development',
            'short' => 'Professional, responsive and conversion-focused websites designed around your business goals.',
            'summary' => 'From a first business website to a full corporate presence, SARVIX designs sites that explain your offer clearly and help customers take the next step.',
            'includes' => ['Business websites', 'Corporate websites', 'Landing pages', 'Lead enquiry systems', 'WhatsApp integration', 'Mobile-first design'],
        ],
        [
            'slug' => 'ecommerce',
            'icon' => 'store',
            'category' => 'Commerce Solutions',
            'title' => 'eCommerce Solutions',
            'short' => 'Complete online stores with product management, payments, orders, customers and scalable eCommerce functionality.',
            'summary' => 'Sell products or services online with a store that matches how your business actually operates - from catalogue to payment to fulfilment.',
            'includes' => ['Product catalogues', 'Payments', 'Order management', 'Customer accounts', 'Inventory-ready stores', 'WhatsApp ordering support'],
        ],
        [
            'slug' => 'custom-software',
            'icon' => 'layers',
            'category' => 'Business Software',
            'title' => 'Custom Software',
            'short' => 'Business-specific software including CRM, ERP, inventory, billing, portals and management systems.',
            'summary' => 'When off-the-shelf tools do not fit, we build software around your process - so teams can manage customers, stock, billing and operations in one place.',
            'includes' => ['CRM', 'ERP', 'Inventory systems', 'Billing software', 'Business portals', 'Internal management tools'],
        ],
        [
            'slug' => 'ai-automation',
            'icon' => 'spark',
            'category' => 'AI & Automation',
            'title' => 'AI & Automation',
            'short' => 'AI integrations and smart automation that reduce repetitive work and improve business efficiency.',
            'summary' => 'We connect AI and automation to real workflows: enquiries, follow-ups, notifications, reporting and internal processes.',
            'includes' => ['AI chatbots', 'Lead automation', 'WhatsApp automation', 'Workflow automation', 'Smart notifications', 'API integrations'],
        ],
        [
            'slug' => 'digital-business',
            'icon' => 'nodes',
            'category' => 'Digital Transformation',
            'title' => 'Digital Business Solutions',
            'short' => 'Tools and systems that help traditional businesses operate and grow digitally.',
            'summary' => 'Move from paper, calls and scattered tools to a connected digital setup - without forcing technology your team cannot use.',
            'includes' => ['Digital catalogues', 'Business profiles', 'Enquiry systems', 'Operations digitisation', 'Customer portals', 'Process mapping'],
        ],
        [
            'slug' => 'digital-growth',
            'icon' => 'trend',
            'category' => 'Marketing & Growth',
            'title' => 'Digital Growth & Marketing',
            'short' => 'Regular marketing, festival marketing, SEO, advertising and digital growth support.',
            'summary' => 'Technology builds the foundation. Marketing helps customers find you, remember you and choose you - especially around seasons and local festivals.',
            'includes' => ['Regular marketing', 'Festival campaigns', 'SEO', 'Paid advertising', 'Social creatives', 'Brand consistency'],
        ],
    ],

    'service_guides' => [
        'web-development' => [
            'best_for' => 'Businesses that need a clear website so customers can find them, understand the offer and enquire.',
            'outcome' => 'A mobile-first site with enquiry and WhatsApp. Delivery from 5–15 working days.',
            'next_label' => 'See website pricing',
            'next_route' => 'pricing',
            'faq' => [
                ['q' => 'How long does a website take?', 'a' => 'Most business websites are ready in 5–15 working days after we have your content and a short briefing.'],
                ['q' => 'What do I need to start?', 'a' => 'Business name, what you sell, a few photos if you have them, and the WhatsApp number customers should reach.'],
                ['q' => 'Can I start small?', 'a' => 'Yes. Start with a clear website. Add a store, software or marketing when the business is ready.'],
            ],
        ],
        'ecommerce' => [
            'best_for' => 'Shops that want to sell online with a catalogue, cart and orders.',
            'outcome' => 'Customers can browse, order and pay without calling you for every item.',
            'next_label' => 'Build your digital store',
            'next_route' => 'pricing',
            'faq' => [
                ['q' => 'Do I need a separate website?', 'a' => 'Not always. The store can be the website. We will say if a simple brochure site is enough first.'],
                ['q' => 'How do customers pay?', 'a' => 'UPI, cards or WhatsApp order - we match how you already sell, then add checkout when you need it.'],
                ['q' => 'Who handles delivery?', 'a' => 'You handle fulfilment. The store captures the order so nothing is lost in chat.'],
            ],
        ],
        'custom-software' => [
            'best_for' => 'Teams that have outgrown spreadsheets and need one system for stock, billing or clients.',
            'outcome' => 'Software shaped around your process, not a generic tool you will not use.',
            'next_label' => 'Book a free consultation',
            'next_route' => null,
            'faq' => [
                ['q' => 'When do I need custom software?', 'a' => 'When spreadsheets or generic tools slow the team down - stock, billing, follow-ups or client work.'],
                ['q' => 'Is this a ready product?', 'a' => 'No. We scope the process first, then build only what your team will use.'],
                ['q' => 'How do we start?', 'a' => 'A short consultation. Then a written scope so you know what is included before work begins.'],
            ],
        ],
        'ai-automation' => [
            'best_for' => 'Businesses that repeat the same enquiry, follow-up or update work every day.',
            'outcome' => 'Fewer missed leads, faster replies and less manual follow-up.',
            'next_label' => 'See AI solution',
            'next_route' => 'solutions.show',
            'next_param' => 'ai-automation',
            'faq' => [
                ['q' => 'Do I need AI on day one?', 'a' => 'No. We automate the work you already repeat - enquiries, follow-ups and notifications. AI is added only where it helps.'],
                ['q' => 'What can you automate?', 'a' => 'Lead capture, WhatsApp replies, routing to the right person, reminders and simple reports.'],
                ['q' => 'Do I need a website first?', 'a' => 'A clear enquiry path helps. If you already sell on WhatsApp, we can start there.'],
            ],
        ],
        'digital-business' => [
            'best_for' => 'Traditional businesses moving from paper, calls and scattered tools to a simple digital setup.',
            'outcome' => 'A connected presence, catalogue and enquiry flow your team can actually use.',
            'next_label' => 'View business solutions',
            'next_route' => 'solutions',
            'faq' => [
                ['q' => 'Is this just a website?', 'a' => 'A website is presence. Digital business also connects catalogue, enquiry and how you operate day to day.'],
                ['q' => 'Do I replace everything at once?', 'a' => 'No. We start with the one change that removes the most friction, then add the next system.'],
                ['q' => 'Who is this for?', 'a' => 'Shops, clinics, traders and service businesses that still run on paper, calls or mixed tools.'],
            ],
        ],
        'digital-growth' => [
            'best_for' => 'Businesses that already have a website or shop and need regular posts and festival creatives.',
            'outcome' => 'Ready-to-post content every month, starting at ₹4,999.',
            'next_label' => 'See marketing packages',
            'next_route' => 'marketing-packages',
            'faq' => [
                ['q' => 'What is included from ₹4,999?', 'a' => 'Regular monthly creatives you can post. Festival and Complete Growth add seasonal campaigns. Full lists are on Marketing Packages.'],
                ['q' => 'Do you post for me?', 'a' => 'We plan, design and send ready-to-post content. You approve. Publishing support can be added if you need it.'],
                ['q' => 'Can I start without a website?', 'a' => 'Possible, but a website makes the content work harder. We will tell you if presence should come first.'],
            ],
        ],
    ],

    'solution_guides' => [
        'retail' => [
            'best_for' => 'Retail and jewellery businesses that need a catalogue customers trust on mobile.',
            'outcome' => 'A polished storefront for collections, enquiry and WhatsApp follow-up.',
            'next_label' => 'See website pricing',
            'next_route' => 'pricing',
        ],
        'professional-services' => [
            'best_for' => 'Advocates, consultants and firms that need a credible site and a clear enquiry path.',
            'outcome' => 'Clients understand the service and can contact you without hunting for a number.',
            'next_label' => 'See website pricing',
            'next_route' => 'pricing',
        ],
        'ecommerce' => [
            'best_for' => 'Businesses ready to take orders online instead of only through calls or chat.',
            'outcome' => 'Catalogue, cart and orders that match how you already sell.',
            'next_label' => 'Build your digital store',
            'next_route' => 'pricing',
        ],
        'business-management' => [
            'best_for' => 'Teams that need CRM, stock or billing in one place instead of scattered sheets.',
            'outcome' => 'A scoped system around your process - not a generic tool you will abandon.',
            'next_label' => 'Book a free consultation',
            'next_route' => null,
        ],
        'ai-automation' => [
            'best_for' => 'Businesses that lose leads because follow-up depends on one person remembering.',
            'outcome' => 'Chat, WhatsApp and lead routing connected to the work you already do.',
            'next_label' => 'View AI service',
            'next_route' => 'services.show',
            'next_param' => 'ai-automation',
        ],
        'kirana' => [
            'best_for' => 'Neighbourhood stores that want a catalogue, WhatsApp orders and a simple digital presence.',
            'outcome' => 'A store customers can browse on their phone. Plans start at ₹14,999.',
            'next_label' => 'See store pricing',
            'next_route' => 'pricing',
        ],
    ],

    'page' => [
        'how_title' => 'A simple path from first chat to launch.',
        'how_text' => 'You always know what happens next. No long onboarding. No stack you will not use.',
        'faq' => [
            ['q' => 'How do we start?', 'a' => 'Book a free consultation or message on WhatsApp. We map what you need now - website, store, software or marketing.'],
            ['q' => 'Do I pay to talk?', 'a' => 'No. Consultation is free. You pay only after you choose a plan or a scoped project.'],
            ['q' => 'Do I need everything at once?', 'a' => 'No. Start with presence or the one system that removes the most friction. Add selling, software and growth later.'],
            ['q' => 'Are there hidden charges?', 'a' => 'GST extra, if applicable. Ad spend, photography and third-party fees are only added if you ask for them.'],
        ],
    ],

    'journey' => [
        [
            'step' => '01',
            'title' => 'Build Your Digital Presence',
            'items' => ['Website', 'Google presence', 'Business profile', 'Digital catalogue'],
        ],
        [
            'step' => '02',
            'title' => 'Start Selling Online',
            'items' => ['eCommerce', 'Online enquiry', 'WhatsApp ordering', 'Payments'],
        ],
        [
            'step' => '03',
            'title' => 'Manage Your Business',
            'items' => ['CRM', 'Inventory', 'Billing', 'Order management', 'Custom software'],
        ],
        [
            'step' => '04',
            'title' => 'Automate Operations',
            'items' => ['AI', 'Workflow automation', 'WhatsApp automation', 'Notifications'],
        ],
        [
            'step' => '05',
            'title' => 'Grow',
            'items' => ['Marketing', 'SEO', 'Advertising', 'Analytics', 'Business intelligence'],
        ],
    ],

    'industries' => [
        [
            'slug' => 'kirana',
            'title' => 'Kirana & Grocery Stores',
            'need' => 'Local shops that want catalogues, WhatsApp orders and simple digital billing.',
            'solutions' => ['Business website', 'Digital catalogue', 'WhatsApp ordering', 'Inventory & billing'],
        ],
        [
            'slug' => 'dairy',
            'title' => 'Dairy Businesses',
            'need' => 'Subscription, delivery and customer records that stay organised every day.',
            'solutions' => ['Customer records', 'Route / delivery support', 'Billing', 'Enquiry website'],
        ],
        [
            'slug' => 'food',
            'title' => 'Restaurants & Food Businesses',
            'need' => 'Menus, ordering and offers that work on mobile and WhatsApp.',
            'solutions' => ['Website & menu', 'Online ordering', 'Festival offers', 'Review-ready presence'],
        ],
        [
            'slug' => 'retail',
            'title' => 'Retail Stores',
            'need' => 'A store that can sell both in-person and online without two separate systems.',
            'solutions' => ['eCommerce', 'Inventory', 'CRM', 'Campaign creatives'],
        ],
        [
            'slug' => 'manufacturing',
            'title' => 'Manufacturers',
            'need' => 'A professional presence plus internal systems for orders, stock and clients.',
            'solutions' => ['Corporate website', 'Dealer portals', 'ERP-style tools', 'Lead capture'],
        ],
        [
            'slug' => 'wholesale',
            'title' => 'Wholesalers',
            'need' => 'Faster order taking, clearer catalogues and fewer spreadsheet errors.',
            'solutions' => ['B2B catalogues', 'Order portals', 'Inventory', 'WhatsApp workflows'],
        ],
        [
            'slug' => 'export',
            'title' => 'Exporters',
            'need' => 'A credible digital face for buyers, with enquiry and document-ready processes.',
            'solutions' => ['Export website', 'Product showcase', 'Enquiry CRM', 'Multilingual content'],
        ],
        [
            'slug' => 'professional',
            'title' => 'Professional Services',
            'need' => 'Trust-building websites and a simple way to manage enquiries and follow-ups.',
            'solutions' => ['Corporate website', 'Appointment / enquiry forms', 'CRM', 'SEO pages'],
        ],
        [
            'slug' => 'healthcare',
            'title' => 'Healthcare Businesses',
            'need' => 'Clear information, appointment enquiries and careful digital communication.',
            'solutions' => ['Clinic website', 'Enquiry workflows', 'Patient communication', 'Local SEO'],
        ],
        [
            'slug' => 'education',
            'title' => 'Education & Coaching',
            'need' => 'Course visibility, admissions enquiries and regular parent or student updates.',
            'solutions' => ['Institute website', 'Admission forms', 'Automation', 'Campaign creatives'],
        ],
        [
            'slug' => 'real-estate',
            'title' => 'Real Estate',
            'need' => 'Property showcase, lead capture and faster follow-up with interested buyers.',
            'solutions' => ['Project websites', 'Lead CRM', 'WhatsApp updates', 'Listing pages'],
        ],
        [
            'slug' => 'startups',
            'title' => 'Startups',
            'need' => 'A focused first product: website, MVP software or automation that can scale.',
            'solutions' => ['MVP websites', 'Custom software', 'AI features', 'Growth setup'],
        ],
        [
            'slug' => 'services',
            'title' => 'Service Businesses',
            'need' => 'A professional online presence and systems that keep jobs, clients and billing in order.',
            'solutions' => ['Service website', 'Booking / enquiry', 'Job management', 'Digital marketing'],
        ],
    ],

    'solution_paths' => [
        [
            'key' => 'starter',
            'title' => 'Starter',
            'for' => 'For businesses that need to establish their digital presence.',
            'includes' => ['Website', 'Business information', 'Lead enquiry', 'WhatsApp integration'],
            'service' => 'Website Development',
        ],
        [
            'key' => 'sell',
            'title' => 'Sell Online',
            'for' => 'For businesses ready to sell digitally.',
            'includes' => ['eCommerce', 'Payments', 'Orders', 'Product management', 'Customer accounts'],
            'service' => 'eCommerce',
        ],
        [
            'key' => 'manage',
            'title' => 'Manage',
            'for' => 'For businesses that want better internal systems.',
            'includes' => ['CRM', 'Inventory', 'Billing', 'ERP', 'Custom portals'],
            'service' => 'Custom Software',
        ],
        [
            'key' => 'automate',
            'title' => 'Automate & Scale',
            'for' => 'For growing businesses.',
            'includes' => ['AI integrations', 'Automation', 'Analytics', 'Custom workflows', 'Advanced software'],
            'service' => 'AI & Automation',
        ],
    ],

    'business_solutions' => [
        [
            'slug' => 'kirana',
            'title' => 'Kirana & Grocery',
            'heading' => 'Smart Digital Solution for Kirana & Grocery Businesses',
            'industry' => 'Local retail',
            'label' => 'LIVE DEMO',
            'summary' => 'Take your store online, showcase products, receive orders and build a stronger digital presence with a solution designed for local retailers.',
            'capabilities' => ['Product catalogue', 'WhatsApp ordering', 'Offers & banners', 'Admin dashboard'],
            'demo' => 'kirana',
            'preview' => 'solutions/kirana-preview.png',
            'source' => 'SARVIX Kirana Solution',
            'business_type' => 'Kirana & Grocery',
        ],
        [
            'slug' => 'retail',
            'title' => 'Retail & Jewellery',
            'heading' => 'Premium digital storefronts for retail and jewellery brands.',
            'industry' => 'Retail',
            'label' => 'LIVE DEMO',
            'summary' => 'A polished catalogue, product stories and enquiry flow for retailers who need to look established online.',
            'capabilities' => ['Luxury catalogue', 'Collections', 'Wishlist & cart', 'Customer accounts'],
            'demo' => 'jewellery-retail',
            'preview' => 'solutions/retail-preview.png',
            'source' => 'SARVIX Solutions',
            'business_type' => 'Retail',
        ],
        [
            'slug' => 'professional-services',
            'title' => 'Professional Services',
            'heading' => 'A credible digital presence for advocates, consultants and firms.',
            'industry' => 'Professional services',
            'label' => 'LIVE DEMO',
            'summary' => 'Practice-ready websites that explain services clearly and make it easy for clients to enquire.',
            'capabilities' => ['Service pages', 'Enquiry flow', 'Trust-led layout', 'Mobile-first design'],
            'demo' => 'professional-services',
            'preview' => 'solutions/professional-preview.png',
            'source' => 'SARVIX Solutions',
            'business_type' => 'Professional Services',
        ],
        [
            'slug' => 'ecommerce',
            'title' => 'eCommerce',
            'heading' => 'Sell products online with catalogues, payments and orders.',
            'industry' => 'Commerce',
            'label' => 'SOLUTION DEMO',
            'summary' => 'From neighbourhood retail to full online stores - selling tools that match how the business actually operates.',
            'capabilities' => ['Products & categories', 'Cart & checkout', 'Order management', 'Customer accounts'],
            'demo' => 'kirana',
            'preview' => 'solutions/kirana-preview.png',
            'source' => 'SARVIX Solutions',
            'business_type' => 'Retail',
        ],
        [
            'slug' => 'business-management',
            'title' => 'Business Management',
            'heading' => 'Systems that help teams manage customers, stock and operations.',
            'industry' => 'Operations',
            'label' => 'CONCEPT',
            'summary' => 'CRM, inventory, billing and internal tools shaped around your process instead of a generic stack.',
            'capabilities' => ['CRM & follow-up', 'Inventory', 'Billing', 'Custom portals'],
            'demo' => null,
            'preview' => null,
            'source' => 'SARVIX Solutions',
            'business_type' => 'Service Business',
        ],
        [
            'slug' => 'ai-automation',
            'title' => 'AI & Automation',
            'heading' => 'Make technology follow up, notify and report without extra tools.',
            'industry' => 'Automation',
            'label' => 'CONCEPT',
            'summary' => 'Chatbots, WhatsApp workflows and lead automation connected to real business processes.',
            'capabilities' => ['AI chatbots', 'Lead automation', 'WhatsApp workflows', 'API integrations'],
            'demo' => null,
            'preview' => null,
            'source' => 'SARVIX Solutions',
            'business_type' => 'Other',
        ],
    ],

    'kirana_plans' => [
        [
            'key' => 'starter',
            'title' => 'Starter',
            'price' => 14999,
            'period' => 'One Time',
            'badge' => 'Start Here',
            'for' => 'Perfect for small businesses starting their digital journey.',
            'insight' => 'Ideal if you only need a professional website with WhatsApp ordering and a product catalogue.',
            'support' => '7 Days Free',
            'training' => 'Free',
            'delivery' => '5–7 Days',
            'ideal' => ['New Shop', 'Low Budget', 'WhatsApp Selling'],
            'features' => [
                'WhatsApp Ordering',
                'Basic Product Catalogue',
                'Contact & Enquiry Form',
                'Google Map Integration',
                'Basic Dashboard',
                'Basic SEO Setup',
            ],
        ],
        [
            'key' => 'business',
            'title' => 'Business',
            'price' => 24999,
            'period' => 'One Time',
            'badge' => 'Most Popular',
            'for' => 'Perfect for growing businesses that update products and run offers often.',
            'insight' => 'Recommended if you update products and run offers often.',
            'support' => '15 Days Free',
            'training' => 'Free',
            'delivery' => '7–10 Days',
            'ideal' => ['Growing Stores', 'Product Updates', 'Promotions'],
            'features' => [
                'Everything in Starter',
                'Advanced Product Search',
                'Product Filters',
                'Banner & Offer Management',
                'Featured Products',
                'Advanced Dashboard',
            ],
        ],
        [
            'key' => 'professional',
            'title' => 'Professional',
            'price' => 29999,
            'period' => 'One Time',
            'badge' => 'Best Choice',
            'for' => 'Complete business solution for stores that want to grow faster.',
            'insight' => 'Best if you want online orders, tracking and a fuller selling system.',
            'support' => '30 Days Free',
            'training' => 'Free',
            'delivery' => '10–15 Days',
            'ideal' => ['Online Selling', 'Customer Accounts', 'Full Orders'],
            'features' => [
                'Everything in Business',
                'Online Order Management',
                'Order Status Tracking',
                'Coupon Management',
                'Sales Analytics',
                'Notification System',
            ],
        ],
    ],

    'kirana_addons' => [
        ['title' => 'Android App', 'price' => 24999, 'note' => 'Optional'],
        ['title' => 'iOS App', 'price' => 34999, 'note' => 'Optional'],
        ['title' => 'New Domain', 'price' => 799, 'note' => 'From / year, provider-based'],
        ['title' => 'Basic Hosting', 'price' => 3000, 'note' => '/ year'],
        ['title' => 'Premium Hosting', 'price' => 6000, 'note' => '/ year'],
    ],

    'ai_features' => [
        'AI Chatbots',
        'Lead Automation',
        'WhatsApp Automation',
        'Workflow Automation',
        'Smart Notifications',
        'AI Content Assistance',
        'Business Data Insights',
        'API Integrations',
    ],

    'marketing' => [
        'frequencies' => ['Monthly', 'Quarterly', 'Half-Yearly', 'Yearly'],
        'hero_title' => 'Your Complete Marketing Team - Starting at ₹4,999/month.',
        'hero_text' => 'We plan, design and send ready-to-post content. You approve. Customers keep seeing your business.',
        'notes' => [
            'tax' => 'GST extra, if applicable. No hidden package charges.',
            'reels' => 'Reels are short videos for Instagram, Facebook and WhatsApp. These are design or motion creatives. Professional video shooting is not included.',
            'festival' => 'Festival creatives follow the SARVIX Festival Calendar - Diwali, Navratri, Independence Day and other important dates.',
            'delivery' => 'On-time delivery means creatives are shared on the regular festival schedule. Early delivery means they are shared sooner, before the festival date.',
            'third_party' => 'Ad spend, photography, video shooting, influencer charges and printing are extra. Ask us only if you need them.',
            'timeline' => 'After a short briefing, the first creatives are shared in 5–7 working days. Then we follow the monthly calendar.',
            'payment' => 'Pay at the start of each plan period. Yearly can be split into 2 payments if needed.',
            'support' => 'WhatsApp support during your active plan. Yearly and Complete Growth get priority replies.',
        ],
        'how_it_works' => [
            ['step' => '01', 'title' => 'Discuss', 'text' => 'We understand your business, language and what you sell.'],
            ['step' => '02', 'title' => 'Content Plan', 'text' => 'You get a simple calendar for posts, stories, reels and festivals.'],
            ['step' => '03', 'title' => 'Design & Approval', 'text' => 'We design. You approve on WhatsApp. Revisions are included.'],
            ['step' => '04', 'title' => 'Publish', 'text' => 'You receive social and WhatsApp-ready files, ready to post.'],
            ['step' => '05', 'title' => 'Monthly Report', 'text' => 'We share what went out and what to do next month.'],
        ],
        'trust' => [
            ['title' => 'No hidden charges', 'text' => 'The package price is the design and content fee. GST and ad spend are shown separately.'],
            ['title' => 'Clear timeline', 'text' => 'First creatives in 5–7 working days after briefing, then a monthly calendar.'],
            ['title' => 'Simple payments', 'text' => 'Pay at the start of the plan. Yearly can be split into 2 payments.'],
            ['title' => 'WhatsApp support', 'text' => 'Ask questions on WhatsApp. Complete Growth and yearly plans get priority.'],
        ],
        'samples' => [
            ['label' => 'Festival post', 'title' => 'Diwali offer', 'meta' => 'Instagram · Square', 'tone' => 'gold'],
            ['label' => 'Everyday post', 'title' => 'New arrival', 'meta' => 'Facebook · Feed', 'tone' => 'navy'],
            ['label' => 'Reel cover', 'title' => '30-sec story', 'meta' => 'Instagram · Reel', 'tone' => 'mist'],
            ['label' => 'WhatsApp status', 'title' => 'Today’s deal', 'meta' => 'WhatsApp · Status', 'tone' => 'green'],
        ],
        'regular' => [
            'key' => 'regular',
            'title' => 'Regular Marketing',
            'heading' => 'Regular Marketing Plans',
            'subheading' => 'Posts, stories and reels every month so customers keep seeing your business.',
            'teaser' => 'Best if you need posts every week - not only on festivals.',
            'best_if' => 'You want to stay visible every week.',
            'service' => 'Regular Marketing',
            'plans' => [
                'monthly' => [
                    'label' => 'Monthly',
                    'duration' => '1 Month',
                    'price' => 4999,
                    'period' => '/ month',
                    'badge' => null,
                    'cta' => 'Get This Plan',
                    'includes' => [
                        '10 Social Media Posts',
                        '8 Stories',
                        '2 Reels / Video Creatives',
                        'Monthly Content Calendar',
                        'Captions & Hashtags',
                        'Brand Consistency',
                        '1 Revision per Post',
                        'Basic Performance Report',
                        'Standard Support',
                    ],
                ],
                'quarterly' => [
                    'label' => 'Quarterly',
                    'duration' => '3 Months',
                    'price' => 13499,
                    'period' => '/ 3 months',
                    'badge' => null,
                    'cta' => 'Get This Plan',
                    'includes' => [
                        '40 Social Media Posts',
                        '30 Stories',
                        '10 Reels / Video Creatives',
                        '3-Month Content Planning',
                        'Captions & Hashtags',
                        'Brand Consistency',
                        'Up to 2 Revisions per Post',
                        'Monthly Performance Report',
                        'Quarterly Strategy Review',
                        'Standard Support',
                    ],
                ],
                'half-yearly' => [
                    'label' => 'Half-Yearly',
                    'duration' => '6 Months',
                    'price' => 24999,
                    'period' => '/ 6 months',
                    'badge' => null,
                    'cta' => 'Get This Plan',
                    'includes' => [
                        '100 Social Media Posts',
                        '50 Stories',
                        '20 Reels / Video Creatives',
                        '6-Month Content Planning',
                        'Captions & Hashtags',
                        'Brand Consistency',
                        'Up to 2 Revisions per Post',
                        'Monthly Performance Report',
                        'Quarterly Strategy Review',
                        'Priority Support',
                    ],
                ],
                'yearly' => [
                    'label' => 'Yearly',
                    'duration' => '12 Months',
                    'price' => 44999,
                    'period' => '/ year',
                    'badge' => 'BEST VALUE',
                    'cta' => 'Get This Plan',
                    'monthly_pace' => [
                        'About 17 posts every month',
                        'About 13 stories every month',
                        'About 4 reels every month',
                        'Captions, hashtags and brand look',
                        'Monthly performance report',
                    ],
                    'includes' => [
                        '200 Social Media Posts',
                        '150 Stories',
                        '50 Reels / Video Creatives',
                        'Annual Marketing Calendar',
                        'Captions & Hashtags',
                        'Brand Consistency',
                        'Up to 2 Revisions per Post',
                        'Monthly Performance Reports',
                        'Quarterly Strategy Reviews',
                        'Priority Support',
                    ],
                ],
            ],
        ],
        'festival' => [
            'key' => 'festival',
            'title' => 'Festival Marketing',
            'heading' => 'Festival Marketing Plans',
            'subheading' => 'Ready-to-post creatives for Diwali, Navratri, national days and other important dates. We follow the SARVIX Festival Calendar.',
            'teaser' => 'Best if you mainly need festival and special-day creatives.',
            'best_if' => 'You mainly need festival and special-day creatives.',
            'service' => 'Festival Marketing',
            'plans' => [
                'monthly' => [
                    'label' => 'Monthly',
                    'duration' => '1 Month',
                    'price' => 1499,
                    'period' => '/ month',
                    'badge' => null,
                    'cta' => 'Get This Plan',
                    'includes' => [
                        'Current Month Festival Coverage',
                        'Major Festival Creatives',
                        'Important National / Special Days',
                        'Client Logo & Business Details',
                        'Social Media Ready Designs',
                        'WhatsApp Ready Designs',
                        '2 Reels / Video Creatives',
                        '1 Language',
                        'Monthly Festival Planning',
                        '1 Revision per Creative',
                        'On-time festival delivery',
                    ],
                ],
                'quarterly' => [
                    'label' => 'Quarterly',
                    'duration' => '3 Months',
                    'price' => 3499,
                    'period' => '/ 3 months',
                    'badge' => null,
                    'cta' => 'Get This Plan',
                    'includes' => [
                        '3-Month Festival Coverage',
                        'Major Festival Creatives',
                        'Important National / Special Days',
                        'Client Branding',
                        'Social Media Ready Designs',
                        'WhatsApp Ready Designs',
                        '10 Reels / Video Creatives',
                        'Up to 2 Languages',
                        'Quarterly Festival Planning',
                        '1 Revision per Creative',
                        'Early festival delivery',
                    ],
                ],
                'half-yearly' => [
                    'label' => 'Half-Yearly',
                    'duration' => '6 Months',
                    'price' => 5999,
                    'period' => '/ 6 months',
                    'badge' => null,
                    'cta' => 'Get This Plan',
                    'includes' => [
                        '6-Month Festival Coverage',
                        'Major Festival Creatives',
                        'National & Important Days',
                        'Client Branding',
                        'Social Media Ready Designs',
                        'WhatsApp Ready Designs',
                        '20 Reels / Video Creatives',
                        'Up to 2 Languages',
                        '6-Month Festival Calendar',
                        'Up to 2 Revisions',
                        'Early festival delivery',
                    ],
                ],
                'yearly' => [
                    'label' => 'Yearly',
                    'duration' => 'Full Year',
                    'price' => 9999,
                    'period' => '/ year',
                    'badge' => 'BEST VALUE',
                    'cta' => 'Get This Plan',
                    'monthly_pace' => [
                        'Festival creatives as dates come',
                        'About 4 reels / month on average',
                        'Social + WhatsApp ready files',
                        'Gujarati / Hindi / English support',
                    ],
                    'includes' => [
                        'Full-Year Festival Coverage',
                        'Major Indian Festivals',
                        'National Days',
                        'Important Business / Special Days',
                        'Client Branding',
                        'Social Media Ready Designs',
                        'WhatsApp Ready Designs',
                        '50 Reels / Video Creatives',
                        'Gujarati / Hindi / English Support',
                        'Complete Annual Festival Calendar',
                        'Up to 2 Revisions',
                        'Early festival delivery',
                    ],
                ],
            ],
        ],
        'growth' => [
            'key' => 'growth',
            'title' => 'Complete Growth',
            'heading' => 'Complete Growth',
            'badge' => 'RECOMMENDED',
            'subheading' => 'Everyday posts plus festival creatives in one plan. Most businesses start here.',
            'teaser' => 'Best if you want both weekly posts and festival creatives.',
            'best_if' => 'You want both weekly posts and festival creatives.',
            'service' => 'Complete Growth',
            'cta' => 'Get This Plan',
            'secondary_cta' => 'Ask on WhatsApp',
            'why' => 'Only ₹1,000 more than Regular Marketing each month - and festival creatives are included. Buying Regular + Festival separately costs more.',
            'plans' => [
                'monthly' => [
                    'label' => 'Monthly',
                    'duration' => '1 Month',
                    'price' => 5999,
                    'period' => '/ month',
                    'badge' => null,
                ],
                'quarterly' => [
                    'label' => 'Quarterly',
                    'duration' => '3 Months',
                    'price' => 15999,
                    'period' => '/ 3 months',
                    'badge' => null,
                ],
                'half-yearly' => [
                    'label' => 'Half-Yearly',
                    'duration' => '6 Months',
                    'price' => 29999,
                    'period' => '/ 6 months',
                    'badge' => null,
                ],
                'yearly' => [
                    'label' => 'Yearly',
                    'duration' => '12 Months',
                    'price' => 49999,
                    'period' => '/ year',
                    'badge' => 'BEST VALUE',
                    'note' => '₹4,999 less than buying Regular + Festival yearly.',
                    'monthly_pace' => [
                        'Everyday posts, stories and reels',
                        'Festival and national-day creatives',
                        'WhatsApp-ready files',
                        'Monthly report + priority support',
                    ],
                ],
            ],
            'includes' => [
                'Everything in Regular Marketing',
                'Everything in Festival Marketing',
                'Social Media Posts',
                'Stories',
                'Reels / Video Creatives',
                'Festival Creatives',
                'National & Special Day Creatives',
                'WhatsApp Ready Creatives',
                'Content Planning',
                'Monthly Report',
                'Priority Support',
            ],
        ],
        'matrix' => [
            'rows' => [
                ['label' => 'Everyday posts, stories & reels', 'regular' => 'Yes', 'festival' => 'No', 'growth' => 'Yes'],
                ['label' => 'Festival & national-day creatives', 'regular' => 'No', 'festival' => 'Yes', 'growth' => 'Yes'],
                ['label' => 'WhatsApp-ready files', 'regular' => 'On request', 'festival' => 'Yes', 'growth' => 'Yes'],
                ['label' => 'Monthly content calendar', 'regular' => 'Yes', 'festival' => 'Festival calendar', 'growth' => 'Yes'],
                ['label' => 'Best if you', 'regular' => 'Need weekly visibility', 'festival' => 'Only need festivals', 'growth' => 'Want both together'],
                ['label' => 'Starts at', 'regular' => '₹4,999 / month', 'festival' => '₹1,499 / month', 'growth' => '₹5,999 / month'],
            ],
        ],
        'comparison' => [
            [
                'key' => 'regular',
                'title' => 'Regular Marketing',
                'if' => 'Need posts every week',
                'gets' => 'Posts, stories and reels all year',
                'text' => 'Best if you need posts every week - not only on festivals.',
            ],
            [
                'key' => 'festival',
                'title' => 'Festival Marketing',
                'if' => 'Only need festival creatives',
                'gets' => 'Festival, national day and special-day creatives',
                'text' => 'Best if you mainly need festival and special-day creatives.',
            ],
            [
                'key' => 'growth',
                'title' => 'Complete Growth',
                'if' => 'Want both together',
                'gets' => 'Weekly posts plus festival creatives',
                'text' => 'Best if you want both weekly posts and festival creatives.',
                'recommended' => true,
            ],
        ],
        'faq' => [
            [
                'q' => 'Which plan should I pick?',
                'a' => 'Need posts every week? Choose Regular Marketing. Only festivals? Choose Festival Marketing. Want both? Complete Growth is the recommended plan - it is only ₹1,000 more than Regular each month and includes festival creatives.',
            ],
            [
                'q' => 'Why is Complete Growth only ₹1,000 more than Regular?',
                'a' => 'Regular is everyday posts only. Complete Growth is Regular plus Festival Marketing. Buying those two separately costs more. For most shops that post weekly and also need Diwali / Navratri creatives, Complete Growth is the better buy.',
            ],
            [
                'q' => 'What do I actually receive?',
                'a' => 'Ready-to-post designs for social media and WhatsApp, plus captions. Reels are short videos made as design or motion creatives. We do not shoot a professional video unless you add that separately.',
            ],
            [
                'q' => 'What is on-time vs early festival delivery?',
                'a' => 'On-time means creatives are shared on the regular festival schedule. Early delivery, on longer Festival plans, means they are shared sooner - before the festival date.',
            ],
            [
                'q' => 'Are Facebook or Google ads included?',
                'a' => 'No. Design and content are included. Ad spend, photography, printing and influencer work are optional extras.',
            ],
            [
                'q' => 'Can I start monthly and change later?',
                'a' => 'Yes. Start monthly if you want to try. Yearly plans cost less than paying month by month.',
            ],
        ],
        'addons' => [
            'Paid Advertising Budget',
            'Google / Meta Ad Spend',
            'Professional Photography',
            'Professional Video Shooting',
            'Influencer Marketing',
            'Printing Costs',
            'Major Custom Campaigns',
            'Advanced SEO',
            'Website Development',
            'Custom Software Development',
        ],
    ],

    'why' => [
        ['title' => 'One Technology Partner', 'text' => 'One team that understands your website, software, automation and growth together.'],
        ['title' => 'Complete Solutions', 'text' => 'From the first webpage to operations software and AI - without switching vendors.'],
        ['title' => 'Business-Focused Approach', 'text' => 'We start with how your business works, then recommend the right technology.'],
        ['title' => 'Scalable Technology', 'text' => 'Start simple. Add selling, systems and automation when you are ready.'],
        ['title' => 'Affordable Growth Path', 'text' => 'Move step by step instead of buying a complicated stack on day one.'],
        ['title' => 'Long-Term Support', 'text' => 'Maintenance, improvements and marketing support as your needs evolve.'],
    ],

    'process' => [
        ['step' => '01', 'title' => 'Understand', 'text' => 'We understand your business, challenges and goals.'],
        ['step' => '02', 'title' => 'Plan', 'text' => 'We recommend the right technology instead of unnecessary features.'],
        ['step' => '03', 'title' => 'Build', 'text' => 'We design and develop your solution.'],
        ['step' => '04', 'title' => 'Launch', 'text' => 'We test, optimize and deploy.'],
        ['step' => '05', 'title' => 'Support & Grow', 'text' => 'We continuously support your business as your needs evolve.'],
    ],

    'portfolio' => [
        [
            'slug' => 'kirana-store',
            'preview' => 'store',
            'title' => 'Retail / Kirana Digital Store',
            'type' => 'Demo Solution',
            'summary' => 'A digital storefront for neighbourhood retail - catalogue, enquiry and WhatsApp-led ordering.',
            'tags' => ['Retail', 'Catalogue', 'WhatsApp'],
        ],
        [
            'slug' => 'restaurant',
            'preview' => 'restaurant',
            'title' => 'Restaurant Ordering Solution',
            'type' => 'Demo Solution',
            'summary' => 'Menu, offers and order capture designed for food businesses that live on mobile.',
            'tags' => ['Food', 'Ordering', 'Mobile'],
        ],
        [
            'slug' => 'business-website',
            'preview' => 'website',
            'title' => 'Business Website',
            'type' => 'Concept Project',
            'summary' => 'A conversion-focused company website with clear services, proof points and enquiry flow.',
            'tags' => ['Web', 'Corporate', 'Leads'],
        ],
        [
            'slug' => 'ecommerce',
            'preview' => 'ecommerce',
            'title' => 'eCommerce Platform',
            'type' => 'Demo Solution',
            'summary' => 'Product, cart, payment and order management for businesses ready to sell online.',
            'tags' => ['eCommerce', 'Payments', 'Orders'],
        ],
        [
            'slug' => 'crm',
            'preview' => 'crm',
            'title' => 'Custom CRM',
            'type' => 'Concept Project',
            'summary' => 'A client and follow-up system shaped around a sales process instead of a generic CRM.',
            'tags' => ['CRM', 'Sales', 'Follow-up'],
        ],
        [
            'slug' => 'inventory',
            'preview' => 'inventory',
            'title' => 'Inventory Management System',
            'type' => 'Concept Project',
            'summary' => 'Stock, billing and movement tracking for businesses that have outgrown spreadsheets.',
            'tags' => ['Inventory', 'Billing', 'Operations'],
        ],
        [
            'slug' => 'ai-automation',
            'preview' => 'ai',
            'title' => 'AI Automation Demo',
            'type' => 'Demo Solution',
            'summary' => 'Lead capture, routing and WhatsApp follow-up with light AI assistance.',
            'tags' => ['AI', 'Automation', 'WhatsApp'],
        ],
    ],

    'ecosystem' => [
        ['name' => 'SARVIX Commerce', 'text' => 'Selling, catalogues and order workflows.'],
        ['name' => 'SARVIX Business', 'text' => 'Operations, CRM and internal systems.'],
        ['name' => 'SARVIX AI', 'text' => 'Assistants, insights and content support.'],
        ['name' => 'SARVIX Automate', 'text' => 'WhatsApp, workflow and notification automation.'],
        ['name' => 'SARVIX Cloud', 'text' => 'A connected home for websites, software and support.'],
    ],

    'form' => [
        'business_types' => [
            'Kirana & Grocery',
            'Dairy',
            'Restaurant & Food',
            'Retail',
            'Manufacturing',
            'Wholesale',
            'Export',
            'Professional Services',
            'Healthcare',
            'Education & Coaching',
            'Real Estate',
            'Startup',
            'Service Business',
            'Other',
        ],
        'services' => [
            'Website Development',
            'eCommerce',
            'Custom Software',
            'AI & Automation',
            'Digital Business Solutions',
            'Digital Marketing',
            'Business Solution',
            'Not sure yet - need guidance',
        ],
        'package_categories' => [
            'Regular Marketing',
            'Festival Marketing',
            'Complete Growth',
        ],
        'plan_durations' => [
            'Monthly',
            'Quarterly',
            'Half-Yearly',
            'Yearly',
        ],
        'package_services' => [
            'Digital Marketing',
        ],
        'budgets' => [
            'To be discussed',
            'Under ₹50,000',
            '₹50,000 – ₹1.5 Lakh',
            '₹1.5 Lakh – ₹5 Lakh',
            '₹5 Lakh+',
        ],
    ],

    'leads' => [
        'default_status' => 'New',
        'statuses' => ['New', 'Contacted', 'Follow-up', 'Converted', 'Lost'],
        'sources' => [
            'Website Contact',
            'Free Consultation',
            'Regular Marketing',
            'Festival Marketing',
            'Complete Growth',
            'WhatsApp',
            'Technology Solution',
            'SARVIX Kirana Solution',
            'SARVIX Demos',
            'SARVIX Solutions',
        ],
    ],
];
