@extends('layouts.app')

@section('title', 'SARVIX Technologies | Technology for Every Business')
@section('description', 'SARVIX Technologies provides websites, eCommerce, custom software, AI automation and complete digital solutions for businesses.')

@section('content')
    @include('sections.home.hero')
    @include('sections.home.trust')
    @include('sections.home.about')
    @include('sections.home.services')
    @include('sections.home.action')
    @include('sections.home.transformation')
    @include('sections.home.industries')
    @include('sections.home.solutions')
    @include('sections.home.ai')
    @include('sections.home.marketing')
    @include('sections.home.why')
    @include('sections.home.process')
    @include('sections.home.portfolio')
    @include('sections.home.future')
    @include('sections.home.cta')
@endsection
